export const mockData = (page = 1) => ({
  page,
  results: [
    {
      adult: false,
      backdrop_path: '/4JNggqfyJWREqb0enzpUMbvIniV.jpg',
      genre_ids: [16, 10751, 35, 14, 18],
      id: 508442,
      original_language: 'en',
      original_title: 'Soul',
      overview:
        'Joe Gardner is a middle school teacher with a love for jazz music. After a successful audition at the Half Note Club, he suddenly gets into an accident that separates his soul from his body and is transported to the You Seminar, a center in which souls develop and gain passions before being transported to a newborn child. Joe must enlist help from the other souls-in-training, like 22, a soul who has spent eons in the You Seminar, in order to get back to Earth.',
      popularity: 75.811,
      poster_path: '/hm58Jw4Lw8OIeECIq5qyPYhAeRJ.jpg',
      release_date: '2020-12-25',
      title: 'Soul',
      video: false,
      vote_average: 8.155,
      vote_count: 9186,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [80],
      id: 393989,
      original_language: 'en',
      original_title: 'Soul',
      overview:
        "Chase, a frustrated artist, lives a bohemian life with lover, Alexis, an enchanting dancer, in their rundown apartment in an artistic niche of the city. His life is thrown into turmoil when Alexis is raped and murdered. Chase's greedy art dealer, Carl, sees this tragedy as a way to capitalize on what once was a unfruitful investment. What follows is a chain reaction of greed by way of mourning Alexis' death. Chase can find only one reason to go on: revenge.",
      popularity: 1.427,
      poster_path: '/1ZvojPXy53WjnvpDCTgCAdt8L3X.jpg',
      release_date: '2016-04-16',
      title: 'Soul',
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [99],
      id: 466487,
      original_language: 'en',
      original_title: 'Soul',
      overview:
        'Soul explores the secrets of gastronomy where two cuisines apparently so opposite in their philosophy, conception and experience, have both earned the highest culinary recognition, three Michelin stars.',
      popularity: 1.192,
      poster_path: '/iBEMNvJZO81ZrROm3Ku0IpNLeH6.jpg',
      release_date: '2016-01-01',
      title: 'Soul',
      video: false,
      vote_average: 4.5,
      vote_count: 2,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [18, 14],
      id: 745074,
      original_language: 'zh',
      original_title: 'Soul',
      overview:
        'A family struggles after the main breadwinner has to quit his teaching job due to illness, and his 70-year-old mother must provide for both of them.',
      popularity: 0.6,
      poster_path: '/aQGH87OpqtYrHqMaQLDBsvtLapR.jpg',
      release_date: '2019-01-01',
      title: 'Soul',
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: '/JvTFgt2JTR9Rp4XGGVGOCSRrC5.jpg',
      genre_ids: [16, 28, 14],
      id: 839100,
      original_language: 'ja',
      original_title: 'ブライト: サムライソウル',
      overview:
        'Izo, a Ronin, and Raiden, an orc, work to bring a young elf girl and the wand she carries to the land of the elves in the north.',
      popularity: 12.715,
      poster_path: '/6FuOW69wl9Bf2kzaVut596sMhZ6.jpg',
      release_date: '2021-10-12',
      title: 'Bright: Samurai Soul',
      video: false,
      vote_average: 5.71,
      vote_count: 50,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [],
      id: 1125713,
      original_language: 'en',
      original_title: 'Soul',
      overview: 'the soul is the key',
      popularity: 0.6,
      poster_path: null,
      release_date: '',
      title: 'Soul',
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [],
      id: 1129795,
      original_language: 'en',
      original_title: 'SOUL',
      overview: 'you have a body. temporarily.',
      popularity: 1.34,
      poster_path: '/aJHdRc9QEsgs3UY6pySmML9MwQn.jpg',
      release_date: '',
      title: 'SOUL',
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: '/tQprwIKzFx83JpM5dVrGRC4UpF.jpg',
      genre_ids: [16, 12, 14, 9648],
      id: 573730,
      original_language: 'ja',
      original_title: '劇場版メイドインアビス 深き魂の黎明',
      overview:
        "A continuation of the epic adventure of plucky Riko and Reg who are joined by their new friend Nanachi. Together they descend into the Abyss' treacherous fifth layer, the Sea of Corpses, and encounter the mysterious Bondrewd, a legendary White Whistle whose shadow looms over Nanachi's troubled past. Bondrewd is ingratiatingly hospitable, but the brave adventurers know things are not always as they seem in the enigmatic Abyss.",
      popularity: 18.479,
      poster_path: '/fsPZdpocYYbvDS2YEE1Xohqo1ni.jpg',
      release_date: '2020-01-17',
      title: 'Made in Abyss: Dawn of the Deep Soul',
      video: false,
      vote_average: 7.969,
      vote_count: 175,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [18],
      id: 892509,
      original_language: 'fr',
      original_title: 'Les âmes sœurs',
      overview:
        'Lieutenant of the French forces engaged in Mali, David Faber is seriously burned during the explosion of his armored vehicle. Repatriated to France for intensive care, he must begin a long convalescence, under the worried but devoted gaze of his sister Jeanne. They meet again in the family house in the Alps, between mountains, lake and forests. Jeanne tries to reconnect her brother with the past, but David, who suffers from amnesia after the accident, does not seem to be interested in reconciling with the man he used to be.',
      popularity: 1.175,
      poster_path: '/kOzfTboDCsjjuILpFGMOjVmMzXI.jpg',
      release_date: '2023-04-12',
      title: 'Soul Mates',
      video: false,
      vote_average: 4.429,
      vote_count: 7,
    },
    {
      adult: false,
      backdrop_path: '/eSSZgM4vMcA4XK2FPptLa9NFsAs.jpg',
      genre_ids: [18, 10749],
      id: 617882,
      original_language: 'ko',
      original_title: '소울메이트',
      overview:
        'Mi-so and Ha-eun meet in elementary school and quickly become best friends. In high school, Ha-eun meets Jin-woo and starts to have feelings for him, but he starts to have feelings for Mi-so. When they all meet again as adults, they are very different people, but they try to remember what friendship is really about.',
      popularity: 18.036,
      poster_path: '/iL0jvWpSVW1uFn9aAoUh3UwzdYA.jpg',
      release_date: '2023-03-15',
      title: 'Soulmate',
      video: false,
      vote_average: 7.1,
      vote_count: 16,
    },
    {
      adult: false,
      backdrop_path: '/abvjxajyplR5sfQH3EqBowO3D9R.jpg',
      genre_ids: [99],
      id: 958151,
      original_language: 'fr',
      original_title: 'Les âmes perdues',
      overview:
        'Twenty-seven thousand photos of corpses, and bodies tortured in detention centers of the Syrian regime, are leaked in 2014 by a mysterious deserter with the code name "Caesar". Because of the geopolitical interests of some countries and the indifference of other nations, international justice refuses to prosecute the regime of Bashar Al Assad responsible for crimes reminiscent of Nazi or Khmer barbarism. Filmed throughout Europe over nearly four years between 2016 and 2020, the film recounts the behind-the-scenes and twists and turns of investigations and proceedings that will lead to the issuance of arrest warrants for the highest officials of Bashar al Assad\'s administration for crimes against humanity.',
      popularity: 2.166,
      poster_path: '/zGM0XjB83T2jvUHBUPwajN9udxh.jpg',
      release_date: '2023-05-03',
      title: 'The Lost Souls of Syria',
      video: false,
      vote_average: 7,
      vote_count: 1,
    },
    {
      adult: false,
      backdrop_path: '/nQRTynJcXF5GRcyEHF09yZIuQ7F.jpg',
      genre_ids: [10402, 99],
      id: 611291,
      original_language: 'ko',
      original_title: '브링 더 소울: 더 무비',
      overview:
        'A glimpse into K-pop group BTS’ world away from the stage, featuring intimate group discussions alongside spectacular concert performances from their world tour.',
      popularity: 10.886,
      poster_path: '/yf1nDk5gFelrE1Z8ioRPKfsSTPt.jpg',
      release_date: '2019-08-07',
      title: 'Bring the Soul: The Movie',
      video: false,
      vote_average: 8.447,
      vote_count: 398,
    },
    {
      adult: false,
      backdrop_path: '/s5BvDOLava3Z8NjAOnT0Xe96iLS.jpg',
      genre_ids: [18, 10749, 14],
      id: 436343,
      original_language: 'hu',
      original_title: 'Testről és lélekről',
      overview:
        'Two introverted people find out by pure chance that they share the same dream every night. They are puzzled, incredulous, a bit frightened. As they hesitantly accept this strange coincidence, they try to recreate in broad daylight what happens in their dream.',
      popularity: 6.804,
      poster_path: '/uguWEoZelSSckxgiQctlkZ6gpfU.jpg',
      release_date: '2017-03-02',
      title: 'On Body and Soul',
      video: false,
      vote_average: 7.227,
      vote_count: 486,
    },
    {
      adult: false,
      backdrop_path: '/8vlu5KfAJhYm3JLyLzHa75jEpKp.jpg',
      genre_ids: [28],
      id: 646332,
      original_language: 'es',
      original_title: 'Alma de héroe',
      overview:
        "A soldier will have a mission of rescuing his partner kidnapped in the Colombian jungle although he will miss a dating with a beautiful girl that is his partner's sister.",
      popularity: 6.16,
      poster_path: '/Am3avSjCB9y7fmqwFY8qIatPpYi.jpg',
      release_date: '2019-05-02',
      title: 'Soul of Hero',
      video: false,
      vote_average: 7.915,
      vote_count: 117,
    },
    {
      adult: false,
      backdrop_path: '/ih2q5hoclUTICLxMzV31vxgpCzR.jpg',
      genre_ids: [10749, 18],
      id: 216,
      original_language: 'de',
      original_title: 'Angst essen Seele auf',
      overview:
        "Emmi Kurowski, a cleaning lady, is lonely in her old age. Her husband died years ago, and her grown children offer little companionship. One night she goes to a bar frequented by Arab immigrants and strikes up a friendship with middle-aged mechanic Ali. Their relationship soon develops into something more, and Emmi's family and neighbors criticize their spontaneous marriage. Soon Emmi and Ali are forced to confront their own insecurities about their future.",
      popularity: 7.062,
      poster_path: '/ce4l56CCzZTiXa9vFbBVi8Jam16.jpg',
      release_date: '1974-06-05',
      title: 'Ali: Fear Eats the Soul',
      video: false,
      vote_average: 7.74,
      vote_count: 333,
    },
    {
      adult: false,
      backdrop_path: '/esftOuvtihGrPLfIGW6hnopsv1L.jpg',
      genre_ids: [35],
      id: 816181,
      original_language: 'tl',
      original_title: "Momshies! Ang Soul Mo'y Akin",
      overview:
        'Three women with totally different lives accidentally get their souls switched as they struggle with the comedic misadventures of their new worlds, they realize that their own lives and families are worth loving and living for. Jolene, a famous person who always has fans in public, Mylene - an overprotected lady who always gets pleasure and love and Karlene - a rich famous social media influencer all switch bodies but their lives did not just change, but their souls switched that leaves them with no choice but to stick together to live the peculiar lives of each other. Karlene then has to convince a group of investors to invest in her near-bankrupt hotel, but no one believes her because she is trapped in Mylene’s body. In the process of all of their imaginative scenarios, they drew closer to each other into becoming the soul sisters they are destined to be.',
      popularity: 2.534,
      poster_path: '/uXY5EWxEZcdeJqR58UOsIM54EFH.jpg',
      release_date: '2021-06-11',
      title: 'Momshies! Your Soul is Mine',
      video: false,
      vote_average: 4,
      vote_count: 1,
    },
    {
      adult: false,
      backdrop_path: '/4df9E3pi99xuD2xSKIj7Mpz8wR9.jpg',
      genre_ids: [53, 27],
      id: 517285,
      original_language: 'ru',
      original_title: 'Проводник',
      overview:
        'Katya has a powerful gift: she sees ghosts. When her twin sister disappears, Katya begins a desperate search. Police insist her sister doesn’t exist, that she is a figment of Katya’s twisted imagination. However, during her search Katya discovers that there is a serial killer loose on the streets, and her sister is one of his victims. There is still hope to save her, but in a dark and mysterious city full of secrets, you can’t trust anyone. Not even yourself...',
      popularity: 5.876,
      poster_path: '/sam9cFSJknPKW4m4fjwj5idRUkf.jpg',
      release_date: '2018-11-29',
      title: 'The Soul Conductor',
      video: false,
      vote_average: 7.013,
      vote_count: 40,
    },
    {
      adult: false,
      backdrop_path: '/hxPi9FOd46WEVajcjhON8m3sihG.jpg',
      genre_ids: [10752, 18, 36],
      id: 567566,
      original_language: 'lv',
      original_title: 'Dvēseļu putenis',
      overview:
        'The love story of sixteen-year-old Arturs is interrupted by the First World War. After losing his mother and his home, he finds some consolation in joining the army, because this is the first time national battalions are allowed in the Russian Empire. But war is nothing like Arturs imagined – no glory, no fairness. It is brutal and painful. Arturs is now completely alone as war takes the lives of his father and brother. Also, no progress is made in the promised quick resolution of the war and timely return home. Within the notion that only he alone cares about returning home and that his homeland is just a playground for other nations, Arturs finds strength for the final battle and eventually returns home to start everything from scratch, just like his newly born country.',
      popularity: 10.509,
      poster_path: '/z3lVSySBEW17JK4k5RZJ5mALHM5.jpg',
      release_date: '2019-11-11',
      title: 'Blizzard of Souls',
      video: false,
      vote_average: 7.332,
      vote_count: 95,
    },
    {
      adult: false,
      backdrop_path: '/4XCP1zmYI0jRzbItgp2a3pIKSJI.jpg',
      genre_ids: [27],
      id: 1018518,
      original_language: 'id',
      original_title: 'Kalian Pantas Mati',
      overview:
        'Rakka has the ability to communicate with the dead. He uses his abilities to stop an evil spirit filled with vengeance against his schoolmates and helps a beautiful ghost to restore his memories.',
      popularity: 4.778,
      poster_path: '/rc3ay29xPyp11psxUIHTebs3l8i.jpg',
      release_date: '2022-10-13',
      title: 'Tainted Soul',
      video: false,
      vote_average: 4,
      vote_count: 2,
    },
    {
      adult: false,
      backdrop_path: '/rlZvVTDl9N2smAJOErCwd0LJXI4.jpg',
      genre_ids: [9648, 878, 53],
      id: 773569,
      original_language: 'zh',
      original_title: '緝魂',
      overview:
        'Wang Shicong, chairman of the famous group, died tragically at home. The prosecutor Liang Wenchao and his wife, Abang, learned during the investigation that the deceased’s long-term partner, Dr. Wan, and his ex-wife’s Son Wang Tianyou, young newlywed wife Li Yan, and even the dead ex-wife, each suspect has an intricate connection. As more clues gradually surfaced, they gradually discovered the rich. The amazing secret hidden behind the murder...',
      popularity: 7.72,
      poster_path: '/hrLX0HY408IFiVdSFytOtqcfLAs.jpg',
      release_date: '2021-01-08',
      title: 'The Soul',
      video: false,
      vote_average: 7.254,
      vote_count: 65,
    },
  ],
  total_pages: 2,
  total_results: 40,
})
