export const mockData = (page = 1) => ({
  page,
  results: [
    {
      adult: false,
      backdrop_path: '/wZMY9X8jtSS5GXFue2lvhgaJkii.jpg',
      id: 42009,
      name: 'Black Mirror',
      original_language: 'en',
      original_name: 'Black Mirror',
      overview:
        "A contemporary British re-working of The Twilight Zone with stories that tap into the collective unease about our modern world. \n\nOver the last ten years, technology has transformed almost every aspect of our lives before we've had time to stop and question it. In every home; on every desk; in every palm - a plasma screen; a monitor; a smartphone - a black mirror of our 21st Century existence.",
      poster_path: '/5UaYsGZOFhjFDwQh6GuLjjA1WlF.jpg',
      media_type: 'tv',
      genre_ids: [10765, 18, 9648],
      popularity: 904.672,
      first_air_date: '2011-12-04',
      vote_average: 8.313,
      vote_count: 4124,
      origin_country: ['GB'],
    },
    {
      adult: false,
      backdrop_path: '/6mOK9j99OFlxGc3ird2jWUeUha9.jpg',
      id: 114472,
      name: 'Secret Invasion',
      original_language: 'en',
      original_name: 'Secret Invasion',
      overview:
        'Nick Fury and Talos discover a faction of shapeshifting Skrulls who have been infiltrating Earth for years.',
      poster_path: '/5rhoPzWGVSsqONBkNbAkMZULNoq.jpg',
      media_type: 'tv',
      genre_ids: [10759, 18, 10765],
      popularity: 178.686,
      first_air_date: '2023-06-21',
      vote_average: 9.0,
      vote_count: 14,
      origin_country: ['US'],
    },
    {
      adult: false,
      backdrop_path: '/nTvM4mhqNlHIvUkI1gVnW6XP7GG.jpg',
      id: 85937,
      name: 'Demon Slayer: Kimetsu no Yaiba',
      original_language: 'ja',
      original_name: '鬼滅の刃',
      overview:
        'It is the Taisho Period in Japan. Tanjiro, a kindhearted boy who sells charcoal for a living, finds his family slaughtered by a demon. To make matters worse, his younger sister Nezuko, the sole survivor, has been transformed into a demon herself. Though devastated by this grim reality, Tanjiro resolves to become a “demon slayer” so that he can turn his sister back into a human, and kill the demon that massacred his family.',
      poster_path: '/xUfRZu2mi8jH6SzQEJGP6tjBuYj.jpg',
      media_type: 'tv',
      genre_ids: [16, 10759, 10765],
      popularity: 372.523,
      first_air_date: '2019-04-06',
      vote_average: 8.693,
      vote_count: 5325,
      origin_country: ['JP'],
    },
    {
      adult: false,
      backdrop_path: '/1V4SPkV3bQvl85zK4FqwTzdfBs4.jpg',
      id: 125988,
      name: 'Silo',
      original_language: 'en',
      original_name: 'Silo',
      overview:
        'In a ruined and toxic future, a community exists in a giant underground silo that plunges hundreds of stories deep. There, men and women live in a society full of regulations they believe are meant to protect them.',
      poster_path: '/zBx1X06G1OlndbXTCZI13FECNz2.jpg',
      media_type: 'tv',
      genre_ids: [10765, 18],
      popularity: 624.64,
      first_air_date: '2023-05-04',
      vote_average: 8.239,
      vote_count: 178,
      origin_country: ['GB', 'US'],
    },
    {
      adult: false,
      backdrop_path: '/xqIhUVrfFVZIHVyj6Rf7zCN8n3l.jpg',
      id: 194583,
      name: 'The Walking Dead: Dead City',
      original_language: 'en',
      original_name: 'The Walking Dead: Dead City',
      overview:
        'Maggie and Negan travel to post-apocalyptic Manhattan - long ago cut off from the mainland. The crumbling city is filled with the dead and denizens who have made it a world full of anarchy, danger, beauty, and terror.',
      poster_path: '/wq3vuQzQgbS83zX3malAFWMsSwX.jpg',
      media_type: 'tv',
      genre_ids: [18, 10759, 10765],
      popularity: 915.163,
      first_air_date: '2023-06-18',
      vote_average: 8.422,
      vote_count: 64,
      origin_country: ['US'],
    },
    {
      adult: false,
      backdrop_path: '/boyxwftKk9NvsXBjmzJWrRveeYO.jpg',
      id: 135251,
      name: 'The Idol',
      original_language: 'en',
      original_name: 'The Idol',
      overview:
        "After a nervous breakdown derailed Jocelyn's last tour, she’s determined to claim her rightful status as the greatest and sexiest pop star in America. Her passions are reignited by Tedros, a nightclub impresario with a sordid past. Will her romantic awakening take her to glorious new heights or the deepest and darkest depths of her soul?",
      poster_path: '/gO9k7t9jSdkkWVG0deMZDpELZGw.jpg',
      media_type: 'tv',
      genre_ids: [18],
      popularity: 640.66,
      first_air_date: '2023-06-04',
      vote_average: 6.5,
      vote_count: 49,
      origin_country: ['US'],
    },
    {
      adult: false,
      backdrop_path: '/zhsEnDNCQX5dlI2wbKzV90pV0B9.jpg',
      id: 127529,
      name: 'Bloodhounds',
      original_language: 'ko',
      original_name: '사냥개들',
      overview:
        'Two young boxers band together with a benevolent moneylender to take down a ruthless loan shark who preys on the financially desperate.',
      poster_path: '/kxU1hhebWZGaz8gkMVi8zkZhzVt.jpg',
      media_type: 'tv',
      genre_ids: [10759, 18, 80],
      popularity: 392.689,
      first_air_date: '2023-06-09',
      vote_average: 8.31,
      vote_count: 71,
      origin_country: ['KR'],
    },
    {
      adult: false,
      backdrop_path: '/q3UGWifvIpdey1T2efX4dSmbZpU.jpg',
      id: 124364,
      name: 'From',
      original_language: 'en',
      original_name: 'From',
      overview:
        'Unravel the mystery of a nightmarish town in middle America that traps all those who enter. As the unwilling residents fight to keep a sense of normalcy and search for a way out, they must also survive the threats of the surrounding forest – including the terrifying creatures that come out when the sun goes down.',
      poster_path: '/pnrv8tfOcWxu4CrB8N7xK0jYJsR.jpg',
      media_type: 'tv',
      genre_ids: [9648, 18, 10765],
      popularity: 1725.762,
      first_air_date: '2022-02-20',
      vote_average: 8.3,
      vote_count: 465,
      origin_country: ['US'],
    },
    {
      adult: false,
      backdrop_path: '/627K48naKH2Y3Rz47Ydra4qktdI.jpg',
      id: 103516,
      name: 'Star Trek: Strange New Worlds',
      original_language: 'en',
      original_name: 'Star Trek: Strange New Worlds',
      overview:
        'Follow Captain Christopher Pike, Science Officer Spock and Number One in the years before Captain Kirk boarded the U.S.S. Enterprise, as they explore new worlds around the galaxy.',
      poster_path: '/7Cp5w4X8xH2x4xDk67C5kMC5ePA.jpg',
      media_type: 'tv',
      genre_ids: [10765],
      popularity: 141.001,
      first_air_date: '2022-05-05',
      vote_average: 8.18,
      vote_count: 330,
      origin_country: ['US'],
    },
    {
      adult: false,
      backdrop_path: '/a6ptrTUH1c5OdWanjyYtAkOuYD0.jpg',
      id: 37854,
      name: 'One Piece',
      original_language: 'ja',
      original_name: 'ワンピース',
      overview:
        'Years ago, the fearsome Pirate King, Gol D. Roger was executed leaving a huge pile of treasure and the famous "One Piece" behind. Whoever claims the "One Piece" will be named the new King of the Pirates.\n\nMonkey D. Luffy, a boy who consumed a "Devil Fruit," decides to follow in the footsteps of his idol, the pirate Shanks, and find the One Piece. It helps, of course, that his body has the properties of rubber and that he\'s surrounded by a bevy of skilled fighters and thieves to help him along the way.\n\nLuffy will do anything to get the One Piece and become King of the Pirates!',
      poster_path: '/dum1wnm6kJOUos0XJqjB8s2UWi9.jpg',
      media_type: 'tv',
      genre_ids: [10759, 35, 16],
      popularity: 105.679,
      first_air_date: '1999-10-20',
      vote_average: 8.719,
      vote_count: 3784,
      origin_country: ['JP'],
    },
    {
      adult: false,
      backdrop_path: '/62bXrOuMYmcn2Mt1T5lja91HlTy.jpg',
      id: 123192,
      name: 'The Crowded Room',
      original_language: 'en',
      original_name: 'The Crowded Room',
      overview:
        'Set in Manhattan during the summer of 1979. When a young man is arrested for a shocking crime—and an unlikely investigator must solve the mystery behind it.',
      poster_path: '/vRmopCFp0j1eJGbILLsYsYzxmL8.jpg',
      media_type: 'tv',
      genre_ids: [18, 80, 9648],
      popularity: 184.817,
      first_air_date: '2023-06-08',
      vote_average: 6.5,
      vote_count: 20,
      origin_country: ['US'],
    },
    {
      adult: false,
      backdrop_path: '/rmmKVswMSMJfBxPAe4rn5jN2Tb0.jpg',
      id: 221300,
      name: 'FUBAR',
      original_language: 'en',
      original_name: 'FUBAR',
      overview:
        'When a father and daughter discover they both secretly work for the CIA, an already dicey undercover mission turns into a dysfunctional family affair.',
      poster_path: '/ryqcPZCEnEahBW4X06QZBUmtavp.jpg',
      media_type: 'tv',
      genre_ids: [10759, 18, 35],
      popularity: 165.428,
      first_air_date: '2023-05-25',
      vote_average: 6.823,
      vote_count: 158,
      origin_country: ['US'],
    },
    {
      adult: false,
      backdrop_path: '/gNPWlhUXhyWiHv9qxr57tvT0WwS.jpg',
      id: 60735,
      name: 'The Flash',
      original_language: 'en',
      original_name: 'The Flash',
      overview:
        'After a particle accelerator causes a freak storm, CSI Investigator Barry Allen is struck by lightning and falls into a coma. Months later he awakens with the power of super speed, granting him the ability to move through Central City like an unseen guardian angel. Though initially excited by his newfound powers, Barry is shocked to discover he is not the only "meta-human" who was created in the wake of the accelerator explosion -- and not everyone is using their new powers for good. Barry partners with S.T.A.R. Labs and dedicates his life to protect the innocent. For now, only a few close friends and associates know that Barry is literally the fastest man alive, but it won\'t be long before the world learns what Barry Allen has become...The Flash.',
      poster_path: '/rg8N7x27Ef6PvlIiioLStf9ZaIO.jpg',
      media_type: 'tv',
      genre_ids: [18, 10765],
      popularity: 776.879,
      first_air_date: '2014-10-07',
      vote_average: 7.793,
      vote_count: 10482,
      origin_country: ['US'],
    },
    {
      adult: false,
      backdrop_path: '/6LWy0jvMpmjoS9fojNgHIKoWL05.jpg',
      id: 1399,
      name: 'Game of Thrones',
      original_language: 'en',
      original_name: 'Game of Thrones',
      overview:
        "Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north. Amidst the war, a neglected military order of misfits, the Night's Watch, is all that stands between the realms of men and icy horrors beyond.",
      poster_path: '/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg',
      media_type: 'tv',
      genre_ids: [10765, 18, 10759],
      popularity: 339.616,
      first_air_date: '2011-04-17',
      vote_average: 8.437,
      vote_count: 21299,
      origin_country: ['US'],
    },
    {
      adult: false,
      backdrop_path: '/oobSrBR9Fw2w3Gk3tfZZUd0R7S7.jpg',
      id: 62286,
      name: 'Fear the Walking Dead',
      original_language: 'en',
      original_name: 'Fear the Walking Dead',
      overview:
        'What did the world look like as it was transforming into the horrifying apocalypse depicted in "The Walking Dead"? This spin-off set in Los Angeles, following new characters as they face the beginning of the end of the world, will answer that question.',
      poster_path: '/sQleNHhKl32QFnSlahb5IHDWcDq.jpg',
      media_type: 'tv',
      genre_ids: [10759, 18],
      popularity: 678.532,
      first_air_date: '2015-08-23',
      vote_average: 7.694,
      vote_count: 4501,
      origin_country: ['US'],
    },
    {
      adult: false,
      backdrop_path: '/nf3Vlxm3C9U1aKUUQHmKFZmxPSc.jpg',
      id: 56570,
      name: 'Outlander',
      original_language: 'en',
      original_name: 'Outlander',
      overview:
        "The story of Claire Randall, a married combat nurse from 1945 who is mysteriously swept back in time to 1743, where she is immediately thrown into an unknown world where her life is threatened. When she is forced to marry Jamie, a chivalrous and romantic young Scottish warrior, a passionate affair is ignited that tears Claire's heart between two vastly different men in two irreconcilable lives.",
      poster_path: '/oftZNfyTVNU7IfOqoGLoT8MGvNs.jpg',
      media_type: 'tv',
      genre_ids: [18, 10765],
      popularity: 474.58,
      first_air_date: '2014-08-09',
      vote_average: 8.2,
      vote_count: 2305,
      origin_country: ['US'],
    },
    {
      adult: false,
      backdrop_path: '/AbUSFDQsprydSoxz4Id1xO9zndm.jpg',
      id: 100883,
      name: 'Never Have I Ever',
      original_language: 'en',
      original_name: 'Never Have I Ever',
      overview:
        "After a traumatic year, all an Indian-American teen wants is to go from pariah to popular -- but friends, family and feeling won't make it easy on her.",
      poster_path: '/hd5fnBixab6IzfUwjC5wfdbX3eM.jpg',
      media_type: 'tv',
      genre_ids: [35, 18],
      popularity: 351.413,
      first_air_date: '2020-04-27',
      vote_average: 8.2,
      vote_count: 1486,
      origin_country: ['US'],
    },
    {
      adult: false,
      backdrop_path: '/A5ITI2kmvcMpQYEPpToTSdtWZzX.jpg',
      id: 226135,
      name: 'Arnold',
      original_language: 'en',
      original_name: 'Arnold',
      overview:
        "This intimate docuseries follows Arnold Schwarzenegger's multifaceted life and career, from bodybuilding champ to Hollywood icon to politician.",
      poster_path: '/o9KmWrG9rbFhB7jWW4vFHTmqv28.jpg',
      media_type: 'tv',
      genre_ids: [99],
      popularity: 89.65,
      first_air_date: '2023-06-07',
      vote_average: 8.491,
      vote_count: 57,
      origin_country: ['US'],
    },
    {
      adult: false,
      backdrop_path: '/brC6qt6QLcWhVl1wsDp1dX9Lim.jpg',
      id: 76331,
      name: 'Succession',
      original_language: 'en',
      original_name: 'Succession',
      overview:
        'Follow the lives of the Roy family as they contemplate their future once their aging father begins to step back from the media and entertainment conglomerate they control.',
      poster_path: '/7HW47XbkNQ5fiwQFYGWdw9gs144.jpg',
      media_type: 'tv',
      genre_ids: [18],
      popularity: 217.603,
      first_air_date: '2018-06-03',
      vote_average: 8.233,
      vote_count: 694,
      origin_country: ['US'],
    },
    {
      adult: false,
      backdrop_path: '/rqbCbjB19amtOtFQbb3K2lgm2zv.jpg',
      id: 1429,
      name: 'Attack on Titan',
      original_language: 'ja',
      original_name: '進撃の巨人',
      overview:
        'Several hundred years ago, humans were nearly exterminated by Titans. Titans are typically several stories tall, seem to have no intelligence, devour human beings and, worst of all, seem to do it for the pleasure rather than as a food source. A small percentage of humanity survived by walling themselves in a city protected by extremely high walls, even taller than the biggest Titans. Flash forward to the present and the city has not seen a Titan in over 100 years. Teenage boy Eren and his foster sister Mikasa witness something horrific as the city walls are destroyed by a Colossal Titan that appears out of thin air. As the smaller Titans flood the city, the two kids watch in horror as their mother is eaten alive. Eren vows that he will murder every single Titan and take revenge for all of mankind.',
      poster_path: '/sHim6U0ANsbzxcmNRYuIubBVQaz.jpg',
      media_type: 'tv',
      genre_ids: [10765, 16, 10759],
      popularity: 63.839,
      first_air_date: '2013-04-07',
      vote_average: 8.659,
      vote_count: 5260,
      origin_country: ['JP'],
    },
  ],
  total_pages: 1000,
  total_results: 20000,
})
