export const movieMockData = (page = 1) => ({
  page,
  results: [
    {
      adult: false,
      backdrop_path: '/4t0oBFrJyweYPt0hocW6RUa0b6H.jpg',
      id: 385687,
      title: 'Fast X',
      original_language: 'en',
      original_title: 'Fast X',
      overview:
        "Over many missions and against impossible odds, Dom Toretto and his family have outsmarted, out-nerved and outdriven every foe in their path. Now, they confront the most lethal opponent they've ever faced: A terrifying threat emerging from the shadows of the past who's fueled by blood revenge, and who is determined to shatter this family and destroy everything—and everyone—that Dom loves, forever.",
      poster_path: '/fiVW06jE7z9YnO4trhaMEdclSiC.jpg',
      media_type: 'movie',
      genre_ids: [28, 80, 53],
      popularity: 2177.081,
      release_date: '2023-05-17',
      video: false,
      vote_average: 7.247,
      vote_count: 933,
    },
    {
      adult: false,
      backdrop_path: '/2I5eBh98Q4aPq8WdQrHdTC8ARhY.jpg',
      id: 569094,
      title: 'Spider-Man: Across the Spider-Verse',
      original_language: 'en',
      original_title: 'Spider-Man: Across the Spider-Verse',
      overview:
        'After reuniting with Gwen Stacy, Brooklyn’s full-time, friendly neighborhood Spider-Man is catapulted across the Multiverse, where he encounters the Spider Society, a team of Spider-People charged with protecting the Multiverse’s very existence. But when the heroes clash on how to handle a new threat, Miles finds himself pitted against the other Spiders and must set out on his own to save those he loves most.',
      poster_path: '/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg',
      media_type: 'movie',
      genre_ids: [28, 12, 16, 878],
      popularity: 2860.755,
      release_date: '2023-05-31',
      video: false,
      vote_average: 8.787,
      vote_count: 972,
    },
    {
      adult: false,
      backdrop_path: '/h8gHn0OzBoaefsYseUByqsmEDMY.jpg',
      id: 603692,
      title: 'John Wick: Chapter 4',
      original_language: 'en',
      original_title: 'John Wick: Chapter 4',
      overview:
        'With the price on his head ever increasing, John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe and forces that turn old friends into foes.',
      poster_path: '/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg',
      media_type: 'movie',
      genre_ids: [28, 53, 80],
      popularity: 4071.868,
      release_date: '2023-03-22',
      video: false,
      vote_average: 7.95,
      vote_count: 2783,
    },
    {
      adult: false,
      backdrop_path: '/9n2tJBplPbgR2ca05hS5CKXwP2c.jpg',
      id: 502356,
      title: 'The Super Mario Bros. Movie',
      original_language: 'en',
      original_title: 'The Super Mario Bros. Movie',
      overview:
        'While working underground to fix a water main, Brooklyn plumbers—and brothers—Mario and Luigi are transported down a mysterious pipe and wander into a magical new world. But when the brothers are separated, Mario embarks on an epic quest to find Luigi.',
      poster_path: '/qNBAXBIQlnOThrVvA6mA2B5ggV6.jpg',
      media_type: 'movie',
      genre_ids: [16, 10751, 12, 14, 35],
      popularity: 3054.106,
      release_date: '2023-04-05',
      video: false,
      vote_average: 7.813,
      vote_count: 4486,
    },
    {
      adult: false,
      backdrop_path: '/ribiMu3iINPxDkofErPxe8jQ8L0.jpg',
      id: 447277,
      title: 'The Little Mermaid',
      original_language: 'en',
      original_title: 'The Little Mermaid',
      overview:
        'The youngest of King Triton’s daughters, and the most defiant, Ariel longs to find out more about the world beyond the sea, and while visiting the surface, falls for the dashing Prince Eric. With mermaids forbidden to interact with humans, Ariel makes a deal with the evil sea witch, Ursula, which gives her a chance to experience life on land, but ultimately places her life – and her father’s crown – in jeopardy.',
      poster_path: '/ym1dxyOk4jFcSl4Q2zmRrA5BEEN.jpg',
      media_type: 'movie',
      genre_ids: [12, 10751, 14, 10749],
      popularity: 1274.636,
      release_date: '2023-05-18',
      video: false,
      vote_average: 6.1,
      vote_count: 562,
    },
    {
      adult: false,
      backdrop_path: '/woJbg7ZqidhpvqFGGMRhWQNoxwa.jpg',
      id: 667538,
      title: 'Transformers: Rise of the Beasts',
      original_language: 'en',
      original_title: 'Transformers: Rise of the Beasts',
      overview:
        "A '90s globetrotting adventure that introduces the Maximals, Predacons, and Terrorcons to the existing battle on earth between Autobots and Decepticons.",
      poster_path: '/gPbM0MK8CP8A174rmUwGsADNYKD.jpg',
      media_type: 'movie',
      genre_ids: [28, 12, 878],
      popularity: 1173.857,
      release_date: '2023-06-06',
      video: false,
      vote_average: 7.7,
      vote_count: 99,
    },
    {
      adult: false,
      backdrop_path: '/bqMWZ5hB7bcI1KK2TH29odwCgWX.jpg',
      id: 493529,
      title: 'Dungeons & Dragons: Honor Among Thieves',
      original_language: 'en',
      original_title: 'Dungeons & Dragons: Honor Among Thieves',
      overview:
        'A charming thief and a band of unlikely adventurers undertake an epic heist to retrieve a lost relic, but things go dangerously awry when they run afoul of the wrong people.',
      poster_path: '/A7AoNT06aRAc4SV89Dwxj3EYAgC.jpg',
      media_type: 'movie',
      genre_ids: [12, 14, 35],
      popularity: 396.557,
      release_date: '2023-03-23',
      video: false,
      vote_average: 7.464,
      vote_count: 1632,
    },
    {
      adult: false,
      backdrop_path: '/51vreLbrGwzAg4WRCHgitWz6Naw.jpg',
      id: 447365,
      title: 'Guardians of the Galaxy Vol. 3',
      original_language: 'en',
      original_title: 'Guardians of the Galaxy Vol. 3',
      overview:
        'Peter Quill, still reeling from the loss of Gamora, must rally his team around him to defend the universe along with protecting one of their own. A mission that, if not completed successfully, could quite possibly lead to the end of the Guardians as we know them.',
      poster_path: '/r2J02Z2OpNTctfOSN1Ydgii51I3.jpg',
      media_type: 'movie',
      genre_ids: [878, 12, 28],
      popularity: 1015.262,
      release_date: '2023-05-03',
      video: false,
      vote_average: 8.125,
      vote_count: 1881,
    },
    {
      adult: false,
      backdrop_path: '/m8JTwHFwX7I7JY5fPe4SjqejWag.jpg',
      id: 640146,
      title: 'Ant-Man and the Wasp: Quantumania',
      original_language: 'en',
      original_title: 'Ant-Man and the Wasp: Quantumania',
      overview:
        "Super-Hero partners Scott Lang and Hope van Dyne, along with with Hope's parents Janet van Dyne and Hank Pym, and Scott's daughter Cassie Lang, find themselves exploring the Quantum Realm, interacting with strange new creatures and embarking on an adventure that will push them beyond the limits of what they thought possible.",
      poster_path: '/qnqGbB22YJ7dSs4o6M7exTpNxPz.jpg',
      media_type: 'movie',
      genre_ids: [28, 12, 878],
      popularity: 1098.822,
      release_date: '2023-02-15',
      video: false,
      vote_average: 6.49,
      vote_count: 3188,
    },
    {
      adult: false,
      backdrop_path: '/suw8eyL3YwE4wfzPQ0cLR02k0Gh.jpg',
      id: 76600,
      title: 'Avatar: The Way of Water',
      original_language: 'en',
      original_title: 'Avatar: The Way of Water',
      overview:
        'Set more than a decade after the events of the first film, learn the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and the tragedies they endure.',
      poster_path: '/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg',
      media_type: 'movie',
      genre_ids: [878, 12, 28],
      popularity: 1098.733,
      release_date: '2022-12-14',
      video: false,
      vote_average: 7.702,
      vote_count: 8401,
    },
    {
      adult: false,
      backdrop_path: '/vQ5T84t8h4N2xAswNFW9fkVIyZq.jpg',
      id: 536437,
      title: 'Hypnotic',
      original_language: 'en',
      original_title: 'Hypnotic',
      overview:
        'A detective becomes entangled in a mystery involving his missing daughter and a secret government program while investigating a string of reality-bending crimes.',
      poster_path: '/3IhGkkalwXguTlceGSl8XUJZOVI.jpg',
      media_type: 'movie',
      genre_ids: [9648, 53, 878],
      popularity: 959.342,
      release_date: '2023-05-11',
      video: false,
      vote_average: 6.586,
      vote_count: 128,
    },
    {
      adult: false,
      backdrop_path: '/6GIpI3X65J6DT2nSTSga9LnanGJ.jpg',
      id: 298618,
      title: 'The Flash',
      original_language: 'en',
      original_title: 'The Flash',
      overview:
        "When his attempt to save his family inadvertently alters the future, Barry Allen becomes trapped in a reality in which General Zod has returned and there are no Super Heroes to turn to. In order to save the world that he is in and return to the future that he knows, Barry's only hope is to race for his life. But will making the ultimate sacrifice be enough to reset the universe?",
      poster_path: '/rktDFPbfHfUbArZ6OOOKsXcv0Bm.jpg',
      media_type: 'movie',
      genre_ids: [878, 28, 12],
      popularity: 380.541,
      release_date: '2023-06-05',
      video: false,
      vote_average: 7.056,
      vote_count: 18,
    },
    {
      adult: false,
      backdrop_path: '/aAgGrfBwna1nO4M2USxwFgK5O0t.jpg',
      id: 713704,
      title: 'Evil Dead Rise',
      original_language: 'en',
      original_title: 'Evil Dead Rise',
      overview:
        'A reunion between two estranged sisters gets cut short by the rise of flesh-possessing demons, thrusting them into a primal battle for survival as they face the most nightmarish version of family imaginable.',
      poster_path: '/5ik4ATKmNtmJU6AYD0bLm56BCVM.jpg',
      media_type: 'movie',
      genre_ids: [53, 27],
      popularity: 1105.239,
      release_date: '2023-04-12',
      video: false,
      vote_average: 7.072,
      vote_count: 1552,
    },
    {
      adult: false,
      backdrop_path: '/xqYfwHPxNiGynos9WJoazDMPP1e.jpg',
      id: 961718,
      title: 'Medellin',
      original_language: 'fr',
      original_title: 'Medellin',
      overview:
        "To save his little brother from the hands of dangerous narcos of the Medellín cartel, Reda has a plan that is as simple as it is totally insane: put together a team and raid Colombia. But this adventure is going to get completely out of control when he decides to kidnap the son of the cartel leader to exchange him for his brother's life.",
      poster_path: '/jKFOQ5LNQuIWGLdB2WhVlSUcS6F.jpg',
      media_type: 'movie',
      genre_ids: [28, 35],
      popularity: 155.204,
      release_date: '2023-06-01',
      video: false,
      vote_average: 5.713,
      vote_count: 61,
    },
    {
      adult: false,
      backdrop_path: '/94TIUEhuwv8PhdIADEvSuwPljS5.jpg',
      id: 840326,
      title: 'Sisu',
      original_language: 'fi',
      original_title: 'Sisu',
      overview:
        'Deep in the wilderness of Lapland, Aatami Korpi is searching for gold but after he stumbles upon Nazi patrol, a breathtaking and gold-hungry chase through the destroyed and mined Lapland wilderness begins.',
      poster_path: '/ygO9lowFMXWymATCrhoQXd6gCEh.jpg',
      media_type: 'movie',
      genre_ids: [28, 10752],
      popularity: 993.679,
      release_date: '2023-01-27',
      video: false,
      vote_average: 7.435,
      vote_count: 624,
    },
    {
      adult: false,
      backdrop_path: '/zRQITMLvVi8z2Xz12Bi6wvbZE82.jpg',
      id: 594767,
      title: 'Shazam! Fury of the Gods',
      original_language: 'en',
      original_title: 'Shazam! Fury of the Gods',
      overview:
        'Billy Batson and his foster siblings, who transform into superheroes by saying "Shazam!", are forced to get back into action and fight the Daughters of Atlas, who they must stop from using a weapon that could destroy the world.',
      poster_path: '/A3ZbZsmsvNGdprRi2lKgGEeVLEH.jpg',
      media_type: 'movie',
      genre_ids: [35, 28, 14],
      popularity: 792.162,
      release_date: '2023-03-15',
      video: false,
      vote_average: 6.7,
      vote_count: 1902,
    },
    {
      adult: false,
      backdrop_path: '/1ntePsIqeklfmrQJqZPncCydsqY.jpg',
      id: 324857,
      title: 'Spider-Man: Into the Spider-Verse',
      original_language: 'en',
      original_title: 'Spider-Man: Into the Spider-Verse',
      overview:
        'Miles Morales is juggling his life between being a high school student and being a spider-man. When Wilson "Kingpin" Fisk uses a super collider, others from across the Spider-Verse are transported to this dimension.',
      poster_path: '/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg',
      media_type: 'movie',
      genre_ids: [28, 12, 16, 878],
      popularity: 893.758,
      release_date: '2018-12-06',
      video: false,
      vote_average: 8.403,
      vote_count: 13008,
    },
    {
      adult: false,
      backdrop_path: '/lntyt4OVDbcxA1l7LtwITbrD3FI.jpg',
      id: 1010581,
      title: 'My Fault',
      original_language: 'es',
      original_title: 'Culpa mía',
      overview:
        "Noah must leave her city, boyfriend, and friends to move into William Leister's mansion, the flashy and wealthy husband of her mother Rafaela. As a proud and independent 17 year old, Noah resists living in a mansion surrounded by luxury. However, it is there where she meets Nick, her new stepbrother, and the clash of their strong personalities becomes evident from the very beginning.",
      poster_path: '/w46Vw536HwNnEzOa7J24YH9DPRS.jpg',
      media_type: 'movie',
      genre_ids: [18, 10749],
      popularity: 304.735,
      release_date: '2023-06-08',
      video: false,
      vote_average: 7.411,
      vote_count: 56,
    },
    {
      adult: false,
      backdrop_path: '/eSVu1FvGPy86TDo4hQbpuHx55DJ.jpg',
      id: 700391,
      title: '65',
      original_language: 'en',
      original_title: '65',
      overview:
        '65 million years ago, the only 2 survivors of a spaceship from Somaris that crash-landed on Earth, must fend off dinosaurs to reach the escape vessel in time before an imminent asteroid strike threatens to destroy the planet.',
      poster_path: '/rzRb63TldOKdKydCvWJM8B6EkPM.jpg',
      media_type: 'movie',
      genre_ids: [878, 28, 12, 53],
      popularity: 224.33,
      release_date: '2023-03-02',
      video: false,
      vote_average: 6.228,
      vote_count: 1184,
    },
    {
      adult: false,
      backdrop_path: '/hiHGRbyTcbZoLsYYkO4QiCLYe34.jpg',
      id: 758323,
      title: "The Pope's Exorcist",
      original_language: 'en',
      original_title: "The Pope's Exorcist",
      overview:
        "Father Gabriele Amorth, Chief Exorcist of the Vatican, investigates a young boy's terrifying possession and ends up uncovering a centuries-old conspiracy the Vatican has desperately tried to keep hidden.",
      poster_path: '/gNPqcv1tAifbN7PRNgqpzY8sEJZ.jpg',
      media_type: 'movie',
      genre_ids: [27, 53],
      popularity: 768.784,
      release_date: '2023-04-05',
      video: false,
      vote_average: 7.251,
      vote_count: 1342,
    },
  ],
  total_pages: 1000,
  total_results: 20000,
})
