export const movieMockData = (page = 1) => ({
  page,
  results: [
    {
      adult: false,
      backdrop_path: '/bmlkLCjrIWnnZzdAQ4uNPG9JFdj.jpg',
      genre_ids: [35, 10751, 14],
      id: 787699,
      original_language: 'en',
      original_title: 'Wonka',
      overview:
        'Willy Wonka – chock-full of ideas and determined to change the world one delectable bite at a time – is proof that the best things in life begin with a dream, and if you’re lucky enough to meet Willy Wonka, anything is possible.',
      popularity: 1035.485,
      poster_path: '/qhb1qOilapbapxWQn9jtRCMwXJF.jpg',
      release_date: '2023-12-06',
      title: 'Wonka',
      video: false,
      vote_average: 7.2,
      vote_count: 410,
    },
    {
      adult: false,
      backdrop_path: '/9jPoyxjiEYPylUIMI3Ntixf8z3M.jpg',
      genre_ids: [16, 12, 35, 10751],
      id: 520758,
      original_language: 'en',
      original_title: 'Chicken Run: Dawn of the Nugget',
      overview:
        "A band of fearless chickens flock together to save poultry-kind from an unsettling new threat: a nearby farm that's cooking up something suspicious.",
      popularity: 913.414,
      poster_path: '/exNtEY8QUuQh9e23wSQjkPxKIU3.jpg',
      release_date: '2023-12-08',
      title: 'Chicken Run: Dawn of the Nugget',
      video: false,
      vote_average: 7.6,
      vote_count: 175,
    },
    {
      adult: false,
      backdrop_path: '/15Fe18IglCCP1jJoj5F529on0IA.jpg',
      genre_ids: [28, 35],
      id: 1029575,
      original_language: 'en',
      original_title: 'The Family Plan',
      overview:
        "Dan Morgan is many things: a devoted husband, a loving father, a celebrated car salesman. He's also a former assassin. And when his past catches up to his present, he's forced to take his unsuspecting family on a road trip unlike any other.",
      popularity: 882.342,
      poster_path: '/jLLtx3nTRSLGPAKl4RoIv1FbEBr.jpg',
      release_date: '2023-12-14',
      title: 'The Family Plan',
      video: false,
      vote_average: 7.6,
      vote_count: 246,
    },
    {
      adult: false,
      backdrop_path: '/zIYROrkHJPYB3VTiW1L9QVgaQO.jpg',
      genre_ids: [28, 35],
      id: 897087,
      original_language: 'en',
      original_title: 'Freelance',
      overview:
        'An ex-special forces operative takes a job to provide security for a journalist as she interviews a dictator, but a military coup breaks out in the middle of the interview, they are forced to escape into the jungle where they must survive.',
      popularity: 704.958,
      poster_path: '/7Bd4EUOqQDKZXA6Od5gkfzRNb0.jpg',
      release_date: '2023-01-05',
      title: 'Freelance',
      video: false,
      vote_average: 6.5,
      vote_count: 345,
    },
    {
      adult: false,
      backdrop_path: '/k1KrbaCMACQiq7EA0Yhw3bdzMv7.jpg',
      genre_ids: [16, 10751, 10402, 14, 35],
      id: 901362,
      original_language: 'en',
      original_title: 'Trolls Band Together',
      overview:
        "When Branch's brother, Floyd, is kidnapped for his musical talents by a pair of nefarious pop-star villains, Branch and Poppy embark on a harrowing and emotional journey to reunite the other brothers and rescue Floyd from a fate even worse than pop-culture obscurity.",
      popularity: 675.752,
      poster_path: '/bkpPTZUdq31UGDovmszsg2CchiI.jpg',
      release_date: '2023-10-12',
      title: 'Trolls Band Together',
      video: false,
      vote_average: 7.2,
      vote_count: 394,
    },
    {
      adult: false,
      backdrop_path: '/9PqD3wSIjntyJDBzMNuxuKHwpUD.jpg',
      genre_ids: [16, 35, 10751],
      id: 1075794,
      original_language: 'en',
      original_title: 'Leo',
      overview:
        'Jaded 74-year-old lizard Leo has been stuck in the same Florida classroom for decades with his terrarium-mate turtle. When he learns he only has one year left to live, he plans to escape to experience life on the outside but instead gets caught up in the problems of his anxious students — including an impossibly mean substitute teacher.',
      popularity: 540.5,
      poster_path: '/pD6sL4vntUOXHmuvJPPZAgvyfd9.jpg',
      release_date: '2023-11-17',
      title: 'Leo',
      video: false,
      vote_average: 7.6,
      vote_count: 622,
    },
    {
      adult: false,
      backdrop_path: '/nHf61UzkfFno5X1ofIhugCPus2R.jpg',
      genre_ids: [35, 12, 14],
      id: 346698,
      original_language: 'en',
      original_title: 'Barbie',
      overview:
        'Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.',
      popularity: 397.506,
      poster_path: '/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg',
      release_date: '2023-07-19',
      title: 'Barbie',
      video: false,
      vote_average: 7.2,
      vote_count: 6383,
    },
    {
      adult: false,
      backdrop_path: '/9n2tJBplPbgR2ca05hS5CKXwP2c.jpg',
      genre_ids: [16, 10751, 12, 14, 35],
      id: 502356,
      original_language: 'en',
      original_title: 'The Super Mario Bros. Movie',
      overview:
        'While working underground to fix a water main, Brooklyn plumbers—and brothers—Mario and Luigi are transported down a mysterious pipe and wander into a magical new world. But when the brothers are separated, Mario embarks on an epic quest to find Luigi.',
      popularity: 366.873,
      poster_path: '/qNBAXBIQlnOThrVvA6mA2B5ggV6.jpg',
      release_date: '2023-04-05',
      title: 'The Super Mario Bros. Movie',
      video: false,
      vote_average: 7.7,
      vote_count: 7487,
    },
    {
      adult: false,
      backdrop_path: '/4uHyfIApZSRXSVEqSuk92PdN8Yx.jpg',
      genre_ids: [10751, 35, 14],
      id: 8871,
      original_language: 'en',
      original_title: 'How the Grinch Stole Christmas',
      overview:
        'The Grinch decides to rob Whoville of Christmas - but a dash of kindness from little Cindy Lou Who and her family may be enough to melt his heart...',
      popularity: 363.921,
      poster_path: '/52EpMoLTTbKAkM6rSrnNHV2mpLF.jpg',
      release_date: '2000-11-17',
      title: 'How the Grinch Stole Christmas',
      video: false,
      vote_average: 6.8,
      vote_count: 6902,
    },
    {
      adult: false,
      backdrop_path: '/h3X1YZXNeklLNKRVOS6DHGRosog.jpg',
      genre_ids: [27, 35, 14],
      id: 287903,
      original_language: 'en',
      original_title: 'Krampus',
      overview:
        'When his dysfunctional family clashes over the holidays, young Max is disillusioned and turns his back on Christmas.  Little does he know, this lack of festive spirit has unleashed the wrath of Krampus: a demonic force of ancient evil intent on punishing non-believers.',
      popularity: 312.401,
      poster_path: '/sAolMRD9rFSTU7tssfFuLEJJa7w.jpg',
      release_date: '2015-11-26',
      title: 'Krampus',
      video: false,
      vote_average: 6.2,
      vote_count: 1994,
    },
    {
      adult: false,
      backdrop_path: '/4fLZUr1e65hKPPVw0R3PmKFKxj1.jpg',
      genre_ids: [16, 35, 10751, 14, 10749],
      id: 976573,
      original_language: 'en',
      original_title: 'Elemental',
      overview:
        'In a city where fire, water, land and air residents live together, a fiery young woman and a go-with-the-flow guy will discover something elemental: how much they have in common.',
      popularity: 303.198,
      poster_path: '/4Y1WNkd88JXmGfhtWR7dmDAo1T2.jpg',
      release_date: '2023-06-14',
      title: 'Elemental',
      video: false,
      vote_average: 7.7,
      vote_count: 3244,
    },
    {
      adult: false,
      backdrop_path: '/5lWIYxYEqWi8j3ZloxXntw3ImBo.jpg',
      genre_ids: [16, 10751, 35, 14],
      id: 360920,
      original_language: 'en',
      original_title: 'The Grinch',
      overview:
        'The Grinch hatches a scheme to ruin Christmas when the residents of Whoville plan their annual holiday celebration.',
      popularity: 294.366,
      poster_path: '/1Bc9VNd9CIHIyJtPKFqSQzrXWru.jpg',
      release_date: '2018-11-08',
      title: 'The Grinch',
      video: false,
      vote_average: 6.8,
      vote_count: 3554,
    },
    {
      adult: false,
      backdrop_path: '/ptz5ETMxDoRRiE69BVuIxJzyTEO.jpg',
      genre_ids: [16, 35, 12, 10751],
      id: 940551,
      original_language: 'en',
      original_title: 'Migration',
      overview:
        'After a migrating duck family alights on their pond with thrilling tales of far-flung places, the Mallard family embarks on a family road trip, from New England, to New York City, to tropical Jamaica.',
      popularity: 277.902,
      poster_path: '/kJG74Y1RxLLjRLYOTrBclWpbvkz.jpg',
      release_date: '2023-12-06',
      title: 'Migration',
      video: false,
      vote_average: 7.4,
      vote_count: 35,
    },
    {
      adult: false,
      backdrop_path: '/AprNYUAS2AJ3xVgg7Wwt00GVvsM.jpg',
      genre_ids: [16, 10751, 28, 878, 35],
      id: 893723,
      original_language: 'en',
      original_title: 'PAW Patrol: The Mighty Movie',
      overview:
        'A magical meteor crash lands in Adventure City and gives the PAW Patrol pups superpowers, transforming them into The Mighty Pups.',
      popularity: 240.084,
      poster_path: '/aTvePCU7exLepwg5hWySjwxojQK.jpg',
      release_date: '2023-09-21',
      title: 'PAW Patrol: The Mighty Movie',
      video: false,
      vote_average: 6.9,
      vote_count: 190,
    },
    {
      adult: false,
      backdrop_path: '/cCIbJZVL3RQXp7CXohkAobhyNaw.jpg',
      genre_ids: [35],
      id: 1172029,
      original_language: 'es',
      original_title: 'Sobreviviendo mis XV',
      overview:
        'Quinceañeras, a magical age... except when your family wants to put you in a bulky dress and make you waltz in front of everyone, which is exactly what happens to Danae shortly after she transfers to a very proper private school.  Now Danae has to manage to balance the demands of her family, those of her new friends and organize a cool, but traditional, but modern, but emotional, but aesthetic, but also grandmother-pleasing Quinceañera party... without dying in the process.',
      popularity: 234.92,
      poster_path: '/kr50u2w3G5L7RqLf6frFliJqPrZ.jpg',
      release_date: '2023-09-21',
      title: 'Sobreviviendo mis XV',
      video: false,
      vote_average: 7.6,
      vote_count: 46,
    },
    {
      adult: false,
      backdrop_path: '/d1RHScaZc7I8j0lDke1c4AxI435.jpg',
      genre_ids: [28, 12, 16, 10751, 35],
      id: 9502,
      original_language: 'en',
      original_title: 'Kung Fu Panda',
      overview:
        'When the Valley of Peace is threatened, lazy Po the panda discovers his destiny as the "chosen one" and trains to become a kung fu hero, but transforming the unsleek slacker into a brave warrior won\'t be easy. It\'s up to Master Shifu and the Furious Five -- Tigress, Crane, Mantis, Viper and Monkey -- to give it a try.',
      popularity: 225.911,
      poster_path: '/wWt4JYXTg5Wr3xBW2phBrMKgp3x.jpg',
      release_date: '2008-06-04',
      title: 'Kung Fu Panda',
      video: false,
      vote_average: 7.3,
      vote_count: 10703,
    },
    {
      adult: false,
      backdrop_path: '/faXT8V80JRhnArTAeYXz0Eutpv9.jpg',
      genre_ids: [12, 14, 16, 35, 10751, 28],
      id: 315162,
      original_language: 'en',
      original_title: 'Puss in Boots: The Last Wish',
      overview:
        'Puss in Boots discovers that his passion for adventure has taken its toll: He has burned through eight of his nine lives, leaving him with only one life left. Puss sets out on an epic journey to find the mythical Last Wish and restore his nine lives.',
      popularity: 222.061,
      poster_path: '/kuf6dutpsT0vSVehic3EZIqkOBt.jpg',
      release_date: '2022-12-07',
      title: 'Puss in Boots: The Last Wish',
      video: false,
      vote_average: 8.3,
      vote_count: 6734,
    },
    {
      adult: false,
      backdrop_path: '/7BdxZXbSkUiVeCRXKD3hi9KYeWm.jpg',
      genre_ids: [16, 10751, 35],
      id: 49444,
      original_language: 'en',
      original_title: 'Kung Fu Panda 2',
      overview:
        'Po is now living his dream as The Dragon Warrior, protecting the Valley of Peace alongside his friends and fellow kung fu masters, The Furious Five - Tigress, Crane, Mantis, Viper and Monkey. But Po’s new life of awesomeness is threatened by the emergence of a formidable villain, who plans to use a secret, unstoppable weapon to conquer China and destroy kung fu. It is up to Po and The Furious Five to journey across China to face this threat and vanquish it. But how can Po stop a weapon that can stop kung fu? He must look to his past and uncover the secrets of his mysterious origins; only then will he be able to unlock the strength he needs to succeed.',
      popularity: 210.932,
      poster_path: '/mtqqD00vB4PGRt20gWtGqFhrkd0.jpg',
      release_date: '2011-05-25',
      title: 'Kung Fu Panda 2',
      video: false,
      vote_average: 7,
      vote_count: 6500,
    },
    {
      adult: false,
      backdrop_path: '/a21obwG9qMSf1qa6oG4ZgpOyMaA.jpg',
      genre_ids: [16, 28, 10751, 35],
      id: 870358,
      original_language: 'en',
      original_title: 'Merry Little Batman',
      overview:
        'This Christmas, Damian Wayne wants to be a superhero like his dad – the one and only Batman. When Damian is left home alone while Batman takes on Gotham’s worst supervillains on Christmas Eve, he stumbles upon a villainous plot to steal Christmas and leaps at the chance to save the day.',
      popularity: 202.76,
      poster_path: '/2J70guF8wcErbYbRgZUBcvShgI1.jpg',
      release_date: '2023-12-08',
      title: 'Merry Little Batman',
      video: false,
      vote_average: 6.6,
      vote_count: 65,
    },
    {
      adult: false,
      backdrop_path: '/bSvUW4JQ6g4QiKvwejcfcPRd4Ke.jpg',
      genre_ids: [12, 35, 10751, 14],
      id: 118,
      original_language: 'en',
      original_title: 'Charlie and the Chocolate Factory',
      overview:
        "A young boy wins a tour through the most magnificent chocolate factory in the world, led by the world's most unusual candy maker.",
      popularity: 202.402,
      poster_path: '/wfGfxtBkhBzQfOZw4S8IQZgrH0a.jpg',
      release_date: '2005-07-13',
      title: 'Charlie and the Chocolate Factory',
      video: false,
      vote_average: 7,
      vote_count: 14218,
    },
  ],
  total_pages: 6237,
  total_results: 124738,
})
