export const tvseriesMockData = (page = 1) => ({
  page,
  results: [
    {
      backdrop_path: '/gMMnf8VRg3Z98WaFmOLr9Jk8pIs.jpg',
      first_air_date: '2015-09-08',
      genre_ids: [35, 10767],
      id: 63770,
      name: 'The Late Show with Stephen Colbert',
      origin_country: ['US'],
      original_language: 'en',
      original_name: 'The Late Show with Stephen Colbert',
      overview:
        'Stephen Colbert brings his signature satire and comedy to The Late Show with Stephen Colbert, the #1 show in late night, where he talks with an eclectic mix of guests about what is new and relevant in the worlds of politics, entertainment, business, music, technology, and more. Featuring bandleader Jon Batiste with his band Stay Human, the Emmy Award-nominated show is broadcast from the historic Ed Sullivan Theater. Stephen Colbert, Chris Licht, Tom Purcell, and Jon Stewart are executive producers. Barry Julien and Denise Rehrig serve as co-executive producers.',
      popularity: 3955.167,
      poster_path: '/9jkThAGYj2yp8jsS6Nriy5mzKFT.jpg',
      vote_average: 6.5,
      vote_count: 216,
    },
    {
      backdrop_path: '/mc3rG5M9dFVjMfaCFNfbD5gu2pK.jpg',
      first_air_date: '2005-02-06',
      genre_ids: [16, 35],
      id: 1433,
      name: 'American Dad!',
      origin_country: ['US'],
      original_language: 'en',
      original_name: 'American Dad!',
      overview:
        "The series focuses on an eccentric motley crew that is the Smith family and their three housemates: Father, husband, and breadwinner Stan Smith; his better half housewife, Francine Smith; their college-aged daughter, Hayley Smith; and their high-school-aged son, Steve Smith. Outside of the Smith family, there are three additional main characters, including Hayley's boyfriend turned husband, Jeff Fischer; the family's man-in-a-goldfish-body pet, Klaus; and most notably the family's zany alien, Roger, who is \"full of masquerades, brazenness, and shocking antics.\"",
      popularity: 3470.015,
      poster_path: '/xnFFz3etm1vftF0ns8RMHA8XdqT.jpg',
      vote_average: 7,
      vote_count: 1921,
    },
    {
      backdrop_path: '/218ZehBKlH8efPRRccmB7bu0oLQ.jpg',
      first_air_date: '2023-09-25',
      genre_ids: [35, 9648, 10766, 18],
      id: 219109,
      name: 'Elas por Elas',
      origin_country: ['BR'],
      original_language: 'pt',
      original_name: 'Elas por Elas',
      overview:
        'Seven friends who met in their youth at an English course meet again 25 years later; Lara, Taís, Helena, Adriana, Renée, Natália and Carol, each of them has a different personality and origin, but they share a deep affection.',
      popularity: 3334.41,
      poster_path: '/m0cvvnhnRXdQhLARx7qt9lz7hTE.jpg',
      vote_average: 5.5,
      vote_count: 34,
    },
    {
      backdrop_path: '/wU1y7snEVYiJBpZ2k1DjIpHgJbx.jpg',
      first_air_date: '1999-01-31',
      genre_ids: [16, 35],
      id: 1434,
      name: 'Family Guy',
      origin_country: ['US'],
      original_language: 'en',
      original_name: 'Family Guy',
      overview:
        "Sick, twisted, politically incorrect and Freakin' Sweet animated series featuring the adventures of the dysfunctional Griffin family. Bumbling Peter and long-suffering Lois have three kids. Stewie (a brilliant but sadistic baby bent on killing his mother and taking over the world), Meg (the oldest, and is the most unpopular girl in town) and Chris (the middle kid, he's not very bright but has a passion for movies). The final member of the family is Brian - a talking dog and much more than a pet, he keeps Stewie in check whilst sipping Martinis and sorting through his own life issues.",
      popularity: 2719.618,
      poster_path: '/hw2vi8agaJZ7oeSvS8uEYgOtK32.jpg',
      vote_average: 7.3,
      vote_count: 4002,
    },
    {
      backdrop_path: '/oUptXLKYtcPqJSuvWFz84qlJwYf.jpg',
      first_air_date: '2002-07-12',
      genre_ids: [35, 80, 18, 9648],
      id: 1695,
      name: 'Monk',
      origin_country: ['US'],
      original_language: 'en',
      original_name: 'Monk',
      overview:
        "Adrian Monk was once a rising star with the San Francisco Police Department, legendary for using unconventional means to solve the department's most baffling cases. But after the tragic (and still unsolved) murder of his wife Trudy, he developed an extreme case of obsessive-compulsive disorder. Now working as a private consultant, Monk continues to investigate cases in the most unconventional ways.",
      popularity: 2328.488,
      poster_path: '/3axGMbUecXXOPSeG47v2i9wK5y5.jpg',
      vote_average: 7.9,
      vote_count: 918,
    },
    {
      backdrop_path: '/7v3bO3pNnyLHLlwETtmyQxKV2Ba.jpg',
      first_air_date: '2015-12-08',
      genre_ids: [35, 10766, 18],
      id: 73362,
      name: "The Ladies' Paradise",
      origin_country: ['IT'],
      original_language: 'it',
      original_name: 'Il paradiso delle signore',
      overview:
        "Follow Teresa Iorio, a young woman who leaves her rural Sicilian hometown for Milan to find work--and much more--at a newly opened department store: The Ladies' Paradise.",
      popularity: 2283.194,
      poster_path: '/7k0D1feQhS59O2k8xkf5UR19LUi.jpg',
      vote_average: 7.6,
      vote_count: 10,
    },
    {
      backdrop_path: '/4W2sH4CXzJ98ScuLGRij1KakzSv.jpg',
      first_air_date: '2023-09-18',
      genre_ids: [10751, 35],
      id: 230525,
      name: 'Unpredictable Family',
      origin_country: ['KR'],
      original_language: 'ko',
      original_name: '우당탕탕 패밀리',
      overview:
        'A romantic family drama about a divorced couple who broke up 30 years ago out of hate, reuniting as in-laws through their children and overcoming long overdue conflicts and enmity.',
      popularity: 2200.517,
      poster_path: '/goMzJ6rxTndGki2pKpyAKuKNXHY.jpg',
      vote_average: 7,
      vote_count: 4,
    },
    {
      backdrop_path: null,
      first_air_date: '2005-09-05',
      genre_ids: [18, 35],
      id: 36361,
      name: 'Ulice',
      origin_country: ['CZ'],
      original_language: 'cs',
      original_name: 'Ulice',
      overview:
        'Ulice is a Czech soap opera produced and broadcast by Nova. In the Czech language Ulice means street.\n\nThe show describes the lives of the Farský, Jordán, Boháč, Nikl, and Liška families and many other people that live in Prague. Their daily battle against real problems of living in a modern world like divorce, love, betrayal and illness or disease. Ulice often shows crime.',
      popularity: 2093.024,
      poster_path: '/3ayWL13P1HeRnyVL9lU9flOdZjq.jpg',
      vote_average: 2.5,
      vote_count: 16,
    },
    {
      backdrop_path: '/yii7eIlaw1MRMfa7FTA6mW8hBUQ.jpg',
      first_air_date: '2023-08-14',
      genre_ids: [35, 10766],
      id: 213026,
      name: 'Fuzue',
      origin_country: ['BR'],
      original_language: 'pt',
      original_name: 'Fuzuê',
      overview:
        "The department store Fuzue, specialized in popular items, is a success led by Nero Braga e Silva. Little does he know that the store's grounds have hidden relics for over 300 years.",
      popularity: 1951.461,
      poster_path: '/zNNFg8z3z7uT817n6M0kHRcYwq1.jpg',
      vote_average: 5.6,
      vote_count: 22,
    },
    {
      backdrop_path: '/6wX6105dCfRqTrwvoQgA8bGxUCo.jpg',
      first_air_date: '2007-02-22',
      genre_ids: [35, 10767],
      id: 1220,
      name: 'The Graham Norton Show',
      origin_country: ['GB'],
      original_language: 'en',
      original_name: 'The Graham Norton Show',
      overview:
        "Each week celebrity guests join Irish comedian Graham Norton to discuss what's being going on around the world that week. The guests poke fun and share their opinions on the main news stories. Graham is often joined by a band or artist to play the show out.",
      popularity: 1895.712,
      poster_path: '/vrbqaBXB8AALynQzpWz6JdCPEJS.jpg',
      vote_average: 7.1,
      vote_count: 224,
    },
    {
      backdrop_path: '/4jlFEf33lWsumqEgyV7DKSGljQa.jpg',
      first_air_date: '2022-12-01',
      genre_ids: [10764, 35],
      id: 214756,
      name: '24-stjerners julekalender',
      origin_country: ['NO'],
      original_language: 'no',
      original_name: '24-stjerners julekalender',
      overview: '',
      popularity: 1849.574,
      poster_path: '/txuVmmwkO1KM3Ml6dQfsBo7ptdQ.jpg',
      vote_average: 6,
      vote_count: 3,
    },
    {
      backdrop_path: '/3O74Pp4zp4jKlQMM78vX2cSVDjR.jpg',
      first_air_date: '2022-12-01',
      genre_ids: [35, 10767],
      id: 215366,
      name: 'Breinholts julekalender',
      origin_country: ['DK'],
      original_language: 'da',
      original_name: 'Breinholts julekalender',
      overview: '',
      popularity: 1827.011,
      poster_path: '/tRFamncuuR35ns0D4eWbmVulP0p.jpg',
      vote_average: 4.3,
      vote_count: 3,
    },
    {
      backdrop_path: '/iU6XAlXlG9GTIRkRYEcQoJYInDf.jpg',
      first_air_date: '1998-10-07',
      genre_ids: [35, 18, 9648, 10765],
      id: 1981,
      name: 'Charmed',
      origin_country: ['US'],
      original_language: 'en',
      original_name: 'Charmed',
      overview:
        'Three sisters (Prue, Piper and Phoebe) reunite and unlock their powers to become the Charmed Ones, the most powerful good witches of all time, whose prophesied destiny is to protect innocent lives from evil beings such as demons and warlocks. Each sister possesses unique magical powers that grow and evolve, while they attempt to maintain normal lives in modern day San Francisco. ',
      popularity: 1776.781,
      poster_path: '/z4bPJ1BWU2EtV69NII2GVvsugQ2.jpg',
      vote_average: 8.2,
      vote_count: 2114,
    },
    {
      backdrop_path: '/5BMwFwNzSidVYArn561acqtktxv.jpg',
      first_air_date: '2005-09-19',
      genre_ids: [35],
      id: 1100,
      name: 'How I Met Your Mother',
      origin_country: ['US'],
      original_language: 'en',
      original_name: 'How I Met Your Mother',
      overview:
        'A father recounts to his children - through a series of flashbacks - the journey he and his four best friends took leading up to him meeting their mother.',
      popularity: 1727.117,
      poster_path: '/b34jPzmB0wZy7EjUZoleXOl2RRI.jpg',
      vote_average: 8.2,
      vote_count: 4496,
    },
    {
      backdrop_path: '/kFyO7f1vxcUwnj32U62jFvdGfPd.jpg',
      first_air_date: '2023-12-01',
      genre_ids: [35, 10767],
      id: 239270,
      name: 'Asbjørns julekalender',
      origin_country: ['NO'],
      original_language: 'no',
      original_name: 'Asbjørns julekalender',
      overview: '',
      popularity: 1679.033,
      poster_path: '/lG3usDELM3VixdqTGWNdjE8QVms.jpg',
      vote_average: 0,
      vote_count: 0,
    },
    {
      backdrop_path: '/pxeqQX4qFQ0cVxPt5SWZENV5BH3.jpg',
      first_air_date: '1989-12-17',
      genre_ids: [10751, 16, 35],
      id: 456,
      name: 'The Simpsons',
      origin_country: ['US'],
      original_language: 'en',
      original_name: 'The Simpsons',
      overview:
        'Set in Springfield, the average American town, the show focuses on the antics and everyday adventures of the Simpson family; Homer, Marge, Bart, Lisa and Maggie, as well as a virtual cast of thousands. Since the beginning, the series has been a pop culture icon, attracting hundreds of celebrities to guest star. The show has also made name for itself in its fearless satirical take on politics, media and American life in general.',
      popularity: 1669.566,
      poster_path: '/vHqeLzYl3dEAutojCO26g0LIkom.jpg',
      vote_average: 8,
      vote_count: 9304,
    },
    {
      backdrop_path: '/mlAzs3tyl5253roHi6eIRbeuONN.jpg',
      first_air_date: '1989-07-05',
      genre_ids: [35],
      id: 1400,
      name: 'Seinfeld',
      origin_country: ['US'],
      original_language: 'en',
      original_name: 'Seinfeld',
      overview:
        "A stand-up comedian and his three offbeat friends weather the pitfalls and payoffs of life in New York City in the '90s. It's a show about nothing.",
      popularity: 1669.093,
      poster_path: '/aCw8ONfyz3AhngVQa1E2Ss4KSUQ.jpg',
      vote_average: 8.3,
      vote_count: 1730,
    },
    {
      backdrop_path: '/2IjkAmxhg4p29rcrp7xSrfKGzyo.jpg',
      first_air_date: '1996-09-27',
      genre_ids: [35, 10751, 10765, 10762],
      id: 605,
      name: 'Sabrina, the Teenage Witch',
      origin_country: ['US'],
      original_language: 'en',
      original_name: 'Sabrina, the Teenage Witch',
      overview:
        'On her sixteenth birthday, Sabrina Spellman discovers she has magical powers. She lives with her 600-year-old aunts Hilda and Zelda as well as talking cat Salem in the fictional town of Westbridge, Massachusetts.',
      popularity: 1536.419,
      poster_path: '/nNhj3coHNVVJPVM7fm5PEYVTCMO.jpg',
      vote_average: 7.9,
      vote_count: 993,
    },
    {
      backdrop_path: '/v3WopDdgHCoNvoBS0V8eVJdurJP.jpg',
      first_air_date: '1971-01-28',
      genre_ids: [35, 99, 18],
      id: 10029,
      name: 'Great Performances',
      origin_country: ['US'],
      original_language: 'en',
      original_name: 'Great Performances',
      overview:
        'The best in the performing arts from across America and around the world including a diverse programming portfolio of classical music, opera, popular song, musical theater, dance, drama, and performance documentaries.',
      popularity: 1499.068,
      poster_path: '/1RD6s6KEbX36Cb99pAoWmU8gkwh.jpg',
      vote_average: 5.9,
      vote_count: 9,
    },
    {
      backdrop_path: '/coHpOy9OJyFiHWeH36cSHMpLUHC.jpg',
      first_air_date: '2003-09-22',
      genre_ids: [35, 18, 10751],
      id: 2691,
      name: 'Two and a Half Men',
      origin_country: ['US'],
      original_language: 'en',
      original_name: 'Two and a Half Men',
      overview:
        "A hedonistic jingle writer's free-wheeling life comes to an abrupt halt when his brother and 10-year-old nephew move into his beach-front house.",
      popularity: 1494.382,
      poster_path: '/A9QDK4OWpv41W27kCv0LXe30k9S.jpg',
      vote_average: 7.5,
      vote_count: 2901,
    },
  ],
  total_pages: 1155,
  total_results: 23096,
})
